# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Relevant Miscellany
tagline:          'Data Science and Drawings of Birds'
description:      'Data Science and Drawings of Birds'
url:              http://dodger487.github.io
baseurl:          /

author:
  name:           'Chris Riederer'
  url:            https://www.criederer.com

email:            OfficialChrisEmail@gmail.com

paginate:         5

# Custom vars
version:          2.1.0 

github:
  repo:           https://github.com/poole/hyde
