# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Relevant Miscellany
tagline:          'Data Science and Drawings of Birds'
description:      'Data Science and Drawings of Birds'
url:              http://dodger487.github.io
baseurl:          /

author:
  name:           'Chris Riederer'
  url:            https://www.criederer.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
